load("@gazelle//:def.bzl", "gazelle")

exports_files([".swcrc"])

###
# Enable gazelle
#

# gazelle:prefix velox.dev
gazelle(name = "gazelle")

####
# Aliases for easier builds
#

alias(
    name = "velox_server",
    actual = "//cmd:velox_server",
)

alias(
    name = "velox_frontend",
    actual = "//public:velox_frontend",
)

####
# Block builds
#

filegroup(
    name = "velox",
    srcs = [
        "//:velox_frontend",
        "//:velox_server",
    ],
)
